"""Project template loader. Templates are plain dicts of {path: content}."""

from __future__ import annotations

import json
from pathlib import Path

from .. import config

_TEMPLATES: dict[str, dict[str, str]] = {}


def _load_templates() -> dict[str, dict[str, str]]:
    path = config.SEED_DIR / "templates.json"
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            return {}
    return _fallback()


def load(name: str) -> dict[str, str]:
    global _TEMPLATES
    if not _TEMPLATES:
        _TEMPLATES = _load_templates()
    if name in _TEMPLATES:
        return _TEMPLATES[name]
    return _TEMPLATES.get("vanilla", {})


def _fallback() -> dict[str, dict[str, str]]:
    return {
        "vanilla": {
            "index.html": "<h1>Hello Orion</h1>\n<script src=\"app.js\"></script>",
            "app.js": "console.log('hello from Orion');",
            "README.md": "# vanilla project\nGenerated by Orion.",
        }
    }
